export const bookmarksData = {
    "books": [
        {"url": "https://learning.oreilly.com/library/view/the-craft-of/9780321434838/app03.html#biblio01_213", "name": "Bibliography - The Craft of System Security"},
        {"url": "http://cacr.uwaterloo.ca/hac/", "name": "Handbook of Applied Cryptography"},
        {"url": "https://www.amazon.com/Elements-Style-Fourth-William-Strunk/dp/020530902X", "name": "Elements of Style"},
        {"url": "https://www.amazon.com/Writing-Science-Papers-Proposals-Funded/dp/0199760241", "name": "Writing Science"},
    ],
    "calculators": [
        {"url": "https://modulocalculator.com/", "name": "Modulo Calculator | Remainder Calculator | All Numbers Modulo Division"},
        {"url": "https://planetcalc.com/3298/", "name": "Online calculator: Extended Euclidean algorithm"},
        {"url": "https://math.stackexchange.com/questions/1226742/rsa-and-extended-euclidian-algorithm", "name": "RSA and extended euclidian algorithm - Mathematics Stack Exchange"},
        {"url": "https://www.calculator.net/log-calculator.html?xv=128&base=2&yv=&x=26&y=28", "name": "Log Calculator"},
        {"url": "https://stackoverflow.com/questions/19732162/generate-prime-number-using-openssl", "name": "bash - Generate prime number using OpenSSL - Stack Overflow"},
        {"url": "https://people.cispa.io/cas.cremers/scyther/", "name": "Scyther tool"},
        {"url": "https://aws.amazon.com/braket/", "name": "Amazon Braket - Amazon Web Services"},
    ],
    "conferences": [
        {"url": "https://www.sigsac.org/ccs/CCS2020/", "name": "ACM CCS 2020 - November 9-13, 2020"},
        {"url": "https://sigsac.org/ccs/CCS2019/index.php/program/program-2/", "name": "Agenda – ACM CCS 2019"},
        {"url": "https://sigsac.org/ccs/CCS2020/index.html", "name": "ACM CCS 2020 - November 9-13, 2020"},
        {"url": "https://crypto.iacr.org/2020/", "name": "Crypto 2020"},
        {"url": "https://www.usenix.org/conferences", "name": "Upcoming USENIX Conferences | USENIX"},
        {"url": "http://www.ieee-security.org/", "name": "IEEE Computer Society&#39;s Technical Committee on Security and Privacy"},
        {"url": "https://www.ieee-security.org/TC/SP2020/program.html", "name": "IEEE Symposium on Security and Privacy 2020"},
        {"url": "https://ches.iacr.org/", "name": "CHES"},
        {"url": "https://oaklandsok.github.io/", "name": "Systematizing SoK"},
    ],
    "iot": [
        {"url": "https://www.shodan.io/", "name": "Shodan"},
        {"url": "https://dzone.com/articles/the-biggest-security-threats-and-challenges-for-io", "name": "The Five Biggest Security Threats and Challenges for IoT - DZone IoT"},
        {"url": "https://www.rambus.com/iot/smart-home/", "name": "Smart Home: Threats and Countermeasures - Rambus"},
    ],
    "protocols": [
        {"url": "https://en.wikipedia.org/wiki/Index_of_cryptography_articles", "name": "Index of cryptography articles - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation", "name": "Block cipher mode of operation - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Transport_Layer_Security", "name": "Transport layer security - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Salt_(cryptography)", "name": "Salt"},
        {"url": "https://en.wikipedia.org/wiki/Stream_cipher", "name": "Stream cipher - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/XOR_cipher", "name": "XOR cipher - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Vigen%C3%A8re_cipher", "name": "Vigenere cipher - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Security_protocol_notation", "name": "Protocol notation - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Alice_and_Bob", "name": "Alice and Bob - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange", "name": "Diffie–Hellman key exchange - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Needham%E2%80%93Schroeder_protocol", "name": "Needham–Schroeder protocol - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Entropic_security", "name": "Entropic security - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Random_oracle", "name": "Random Oracle - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Padding_oracle_attack", "name": "Padding oracle attack - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Hash_function", "name": "Hash function"},
        {"url": "https://en.wikipedia.org/wiki/Public-key_cryptography", "name": "Public key cryptography (asymmetric)"},
        {"url": "https://en.wikipedia.org/wiki/Symmetric-key_algorithm", "name": "Symmetric key algorithm"},
        {"url": "https://en.wikipedia.org/wiki/SHA-3", "name": "SHA-3 - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/MD5", "name": "MD5 - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Birthday_problem", "name": "Birthday paradox - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Ciphertext_stealing", "name": "Ciphertext stealing - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Rainbow_table", "name": "Rainbow table - Wikipedia"},
        {"url": "https://www.openssl.org/", "name": "OPEN SSL"},
        {"url": "https://brilliant.org/wiki/rsa-encryption/", "name": "RSA Encryption | Brilliant Math & Science Wiki"},
        {"url": "https://web.mit.edu/kerberos/", "name": "Kerberos: The Network Authentication Protocol"},
        {"url": "https://en.wikipedia.org/wiki/Bell%E2%80%93LaPadula_model", "name": "Bell–LaPadula model - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Quantum_superposition", "name": "Quantum superposition - Wikipedia"},
        {"url": "https://en.wikipedia.org/wiki/Fiat%E2%80%93Shamir_heuristic", "name": "Fiat Shamir heuristic - Wikipedia"},
    ],
    "papers": [
        {"url": "http://pages.cs.wisc.edu/~rist/642-spring-2014/shannon-secrecy.pdf", "name": "Communication Theory of Secrecy Systems - C.E. Shannon 1949"},
        {"url": "https://www.cs.utexas.edu/~shmat/shmat_ccs12.pdf", "name": "The Most Dangerous Code in the World"},
        {"url": "https://academic.oup.com/cybersecurity/article/1/1/69/2367066", "name": "Keys under doormats: mandating insecurity by requiring government access to all data and communications ‡ | Journal of Cybersecurity | Oxford Academic"},
        {"url": "https://www.cs.umd.edu/class/fall2018/cmsc818O/papers/ps-and-qs.pdf", "name": "Mining Your Ps and Qs: Detection of Widespread Weak Keys in Network Devices"},
        {"url": "http://web.archive.org/web/20171002221541/https://medium.com/@altcoinio/slack-api-for-icos-de61df6448c3", "name": "The week we tried (and failed) to stop the @slackbot reminder exploit - C Franklin"},
        {"url": "https://covid19.apple.com/contacttracing", "name": "Privacy-Preserving Contact Tracing - Apple and Google"},
        {"url": "https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-CryptographySpecificationv1.2.pdf?1", "name": "Exposure Notification - Cryptography Specification"},
    ],
    "people": [
        {"url": "https://en.wikipedia.org/wiki/John_von_Neumann", "name": "John von Neumann - using arithmetic for randomness is sin"},
        {"url": "https://en.wikipedia.org/wiki/Alex_Halderman", "name": "Alex Haldermann - security of electronic voting"},
        {"url": "https://scholar.google.com/citations?user=jaITaUcAAAAJ&hl=en", "name": "Benjamin Livshits"},
    ],
    "universities":[
        {"url": "http://oxfordquantum.org/", "name": "Oxford Quantum"},
        {"url": "https://www2.physics.ox.ac.uk/node/841", "name": "Centre for Quantum Computation | University of Oxford Department of Physics"},
        {"url": "https://www.esat.kuleuven.be/cosic/cosic-research/symmetric-key-cryptography-team/", "name": "Symmetric Key Cryptography Team | COSIC"},
        {"url": "https://www.royalholloway.ac.uk/studying-here/postgraduate/mathematics/mathematics-of-cryptography-and-communications/", "name": "Mathematics of Cryptography and Communications MSc | Royal Holloway, University of London"},
    ]
}
